// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdPkWpRSbE9AM9KmPT4ogwhAz9EXjJ89g',
    appId: '1:346907814975:web:1225f610f5ffcb81b41c8a',
    messagingSenderId: '346907814975',
    projectId: 'my-pet-project177512',
    authDomain: 'my-pet-project177512.firebaseapp.com',
    storageBucket: 'my-pet-project177512.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVH6WiLilrNpE0p07z__awOdAUyjSuj8M',
    appId: '1:346907814975:android:b987c116abbebff9b41c8a',
    messagingSenderId: '346907814975',
    projectId: 'my-pet-project177512',
    storageBucket: 'my-pet-project177512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcxX8iBsn-oSyGlkDsH7L6cLJIV1ZpT0',
    appId: '1:346907814975:ios:1c5344a6e4df197bb41c8a',
    messagingSenderId: '346907814975',
    projectId: 'my-pet-project177512',
    storageBucket: 'my-pet-project177512.firebasestorage.app',
    iosBundleId: 'com.example.myPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcxX8iBsn-oSyGlkDsH7L6cLJIV1ZpT0',
    appId: '1:346907814975:ios:1c5344a6e4df197bb41c8a',
    messagingSenderId: '346907814975',
    projectId: 'my-pet-project177512',
    storageBucket: 'my-pet-project177512.firebasestorage.app',
    iosBundleId: 'com.example.myPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdPkWpRSbE9AM9KmPT4ogwhAz9EXjJ89g',
    appId: '1:346907814975:web:a0372f6cc8380b95b41c8a',
    messagingSenderId: '346907814975',
    projectId: 'my-pet-project177512',
    authDomain: 'my-pet-project177512.firebaseapp.com',
    storageBucket: 'my-pet-project177512.firebasestorage.app',
  );
}
